def channel_law_center(
    r_rigid,
    r_tube_in,
    r_tube_out,
    r_bend,
):
    channel_laws = [
        {"type": "rigid", "R": r_rigid},  # [  0   6]
        {"type": "rigid", "R": r_rigid},  # [  0   7]
        {"type": "rigid", "R": r_rigid},  # [  1   7]
        {"type": "rigid", "R": r_rigid},  # [  1   8]
        {"type": "toponly"},  # [  2   8]
        {"type": "toponly"},  # [  2   9]
        {"type": "toponly"},  # [  3   9]
        {"type": "toponly"},  # [  3  10]
        {"type": "rigid", "R": r_rigid},  # [  4  10]
        {"type": "rigid", "R": r_rigid},  # [  4  11]
        {"type": "rigid", "R": r_rigid},  # [  5  11]
        {"type": "rigid", "R": r_rigid},  # [  5  12]
        {"type": "rigid", "R": r_rigid},  # [  6  13]
        {"type": "rigid", "R": r_rigid},  # [  7  14]
        {"type": "toponly"},  # [  8  15]
        {"type": "topbottom"},  # [  9  16]
        {"type": "toponly"},  # [ 10  17]
        {"type": "rigid", "R": r_rigid},  # [ 11  18]
        {"type": "rigid", "R": r_rigid},  # [ 12  19]
        {"type": "rigid", "R": r_rigid},  # [ 13  20]
        {"type": "rigid", "R": r_rigid},  # [ 14  20]
        {"type": "rigid", "R": r_rigid},  # [ 14  21]
        {"type": "toponly"},  # [ 15  21]
        {"type": "topbottom"},  # [ 15  22]
        {"type": "topbottom"},  # [ 16  22]
        {"type": "topbottom"},  # [ 16  23]
        {"type": "topbottom"},  # [ 17  23]
        {"type": "toponly"},  # [ 17  24]
        {"type": "rigid", "R": r_rigid},  # [ 18  24]
        {"type": "rigid", "R": r_rigid},  # [ 18  25]
        {"type": "rigid", "R": r_rigid},  # [ 19  25]
        {"type": "rigid", "R": r_rigid},  # [ 20  26]
        {"type": "toponly"},  # [ 21  27]
        {"type": "topbottom"},  # [ 22  28]
        {"type": "topbottom"},  # [ 23  29]
        {"type": "toponly"},  # [ 24  30]
        {"type": "rigid", "R": r_rigid},  # [ 25  31]
        {"type": "rigid", "R": r_rigid},  # [ 26  32]
        {"type": "rigid", "R": r_rigid},  # [ 26  33]
        {"type": "rigid", "R": r_rigid},  # [ 27  33]
        {"type": "toponly"},  # [ 27  34]
        {"type": "topbottom"},  # [ 28  34]
        {"type": "topbottom"},  # [ 28  35]
        {"type": "topbottom"},  # [ 29  35]
        {"type": "topbottom"},  # [ 29  36]
        {"type": "toponly"},  # [ 30  36]
        {"type": "rigid", "R": r_rigid},  # [ 30  37]
        {"type": "rigid", "R": r_rigid},  # [ 31  37]
        {"type": "rigid", "R": r_rigid},  # [ 31  38]
        {"type": "rigid", "R": r_rigid},  # [ 32  39]
        {"type": "rigid", "R": r_rigid},  # [ 33  40]
        {"type": "toponly"},  # [ 34  41]
        {"type": "topbottom"},  # [ 35  42]
        {"type": "toponly"},  # [ 36  43]
        {"type": "rigid", "R": r_rigid},  # [ 37  44]
        {"type": "rigid", "R": r_rigid},  # [ 38  45]
        {"type": "rigid", "R": r_rigid},  # [ 39  46]
        {"type": "rigid", "R": r_rigid},  # [ 40  46]
        {"type": "rigid", "R": r_rigid},  # [ 40  47]
        {"type": "toponly"},  # [ 41  47]
        {"type": "topbottom"},  # [ 41  48]
        {"type": "topbottom"},  # [ 42  48]
        {"type": "topbottom"},  # [ 42  49]
        {"type": "topbottom"},  # [ 43  49]
        {"type": "toponly"},  # [ 43  50]
        {"type": "rigid", "R": r_rigid},  # [ 44  50]
        {"type": "rigid", "R": r_rigid},  # [ 44  51]
        {"type": "rigid", "R": r_rigid},  # [ 45  51]
        {"type": "rigid", "R": r_rigid},  # [ 46  52]
        {"type": "toponly"},  # [ 47  53]
        {"type": "topbottom"},  # [ 48  54]
        {"type": "topbottom"},  # [ 49  55]
        {"type": "toponly"},  # [ 50  56]
        {"type": "rigid", "R": r_rigid},  # [ 51  57]
        {"type": "rigid", "R": r_rigid},  # [ 52  58]
        {"type": "rigid", "R": r_rigid},  # [ 52  59]
        {"type": "rigid", "R": r_rigid},  # [ 53  59]
        {"type": "toponly"},  # [ 53  60]
        {"type": "topbottom"},  # [ 54  60]
        {"type": "topbottom"},  # [ 54  61]
        {"type": "topbottom"},  # [ 55  61]
        {"type": "topbottom"},  # [ 55  62]
        {"type": "toponly"},  # [ 56  62]
        {"type": "rigid", "R": r_rigid},  # [ 56  63]
        {"type": "rigid", "R": r_rigid},  # [ 57  63]
        {"type": "rigid", "R": r_rigid},  # [ 57  64]
        {"type": "rigid", "R": r_rigid},  # [ 58  65]
        {"type": "rigid", "R": r_rigid},  # [ 59  66]
        {"type": "toponly"},  # [ 60  67]
        {"type": "topbottom"},  # [ 61  68]
        {"type": "toponly"},  # [ 62  69]
        {"type": "rigid", "R": r_rigid},  # [ 63  70]
        {"type": "rigid", "R": r_rigid},  # [ 64  71]
        {"type": "rigid", "R": r_rigid},  # [ 65  72]
        {"type": "rigid", "R": r_rigid},  # [ 66  72]
        {"type": "rigid", "R": r_rigid},  # [ 66  73]
        {"type": "toponly"},  # [ 67  73]
        {"type": "topbottom"},  # [ 67  74]
        {"type": "topbottom"},  # [ 68  74]
        {"type": "topbottom"},  # [ 68  75]
        {"type": "topbottom"},  # [ 69  75]
        {"type": "toponly"},  # [ 69  76]
        {"type": "rigid", "R": r_rigid},  # [ 70  76]
        {"type": "rigid", "R": r_rigid},  # [ 70  77]
        {"type": "rigid", "R": r_rigid},  # [ 71  77]
        {"type": "rigid", "R": r_rigid},  # [ 72  78]
        {"type": "toponly"},  # [ 73  79]
        {"type": "topbottom"},  # [ 74  80]
        {"type": "topbottom"},  # [ 75  81]
        {"type": "toponly"},  # [ 76  82]
        {"type": "rigid", "R": r_rigid},  # [ 77  83]
        {"type": "rigid", "R": r_rigid},  # [ 78  84]
        {"type": "rigid", "R": r_rigid},  # [ 78  85]
        {"type": "rigid", "R": r_rigid},  # [ 79  85]
        {"type": "toponly"},  # [ 79  86]
        {"type": "topbottom"},  # [ 80  86]
        {"type": "topbottom"},  # [ 80  87]
        {"type": "topbottom"},  # [ 81  87]
        {"type": "topbottom"},  # [ 81  88]
        {"type": "toponly"},  # [ 82  88]
        {"type": "rigid", "R": r_rigid},  # [ 82  89]
        {"type": "rigid", "R": r_rigid},  # [ 83  89]
        {"type": "rigid", "R": r_rigid},  # [ 83  90]
        {"type": "rigid", "R": r_rigid},  # [ 84  91]
        {"type": "rigid", "R": r_rigid},  # [ 85  92]
        {"type": "toponly"},  # [ 86  93]
        {"type": "topbottom"},  # [ 87  94]
        {"type": "toponly"},  # [ 88  95]
        {"type": "rigid", "R": r_rigid},  # [ 89  96]
        {"type": "rigid", "R": r_rigid},  # [ 90  97]
        {"type": "rigid", "R": r_rigid},  # [ 91  98]
        {"type": "rigid", "R": r_rigid},  # [ 92  98]
        {"type": "rigid", "R": r_rigid},  # [ 92  99]
        {"type": "rigid", "R": r_rigid},  # [ 93  99]
        {"type": "toponly"},  # [ 93 100]
        {"type": "toponly"},  # [ 94 100]
        {"type": "toponly"},  # [ 94 101]
        {"type": "toponly"},  # [ 95 101]
        {"type": "rigid", "R": r_rigid},  # [ 95 102]
        {"type": "rigid", "R": r_rigid},  # [ 96 102]
        {"type": "rigid", "R": r_rigid},  # [ 96 103]
        {"type": "rigid", "R": r_rigid},  # [ 97 103]
        {"type": "rigid", "R": r_tube_in},  # [105 104]
        {"type": "rigid", "R": r_bend},  # [104   2]
        {"type": "rigid", "R": r_bend},  # [104   3]
        {"type": "rigid", "R": r_bend},  # [ 98 106]
        {"type": "rigid", "R": r_bend},  # [ 99 106]
        {"type": "rigid", "R": r_tube_out},  # [106 107]
        {"type": "rigid", "R": r_bend},  # [100 108]
        {"type": "rigid", "R": r_bend},  # [101 108]
        {"type": "rigid", "R": r_tube_out},  # [108 109]
        {"type": "rigid", "R": r_bend},  # [102 110]
        {"type": "rigid", "R": r_bend},  # [103 110]
        {"type": "rigid", "R": r_tube_out},  # [110 111]
    ]

    return channel_laws


def channel_law_rigid(
    r_rigid,
    r_tube_in,
    r_tube_out,
    r_bend,
):
    channel_laws = [
        {"type": "rigid", "R": r_rigid},  # [  0   6]
        {"type": "rigid", "R": r_rigid},  # [  0   7]
        {"type": "rigid", "R": r_rigid},  # [  1   7]
        {"type": "rigid", "R": r_rigid},  # [  1   8]
        {"type": "rigid", "R": r_rigid},  # [  2   8]
        {"type": "rigid", "R": r_rigid},  # [  2   9]
        {"type": "rigid", "R": r_rigid},  # [  3   9]
        {"type": "rigid", "R": r_rigid},  # [  3  10]
        {"type": "rigid", "R": r_rigid},  # [  4  10]
        {"type": "rigid", "R": r_rigid},  # [  4  11]
        {"type": "rigid", "R": r_rigid},  # [  5  11]
        {"type": "rigid", "R": r_rigid},  # [  5  12]
        {"type": "rigid", "R": r_rigid},  # [  6  13]
        {"type": "rigid", "R": r_rigid},  # [  7  14]
        {"type": "rigid", "R": r_rigid},  # [  8  15]
        {"type": "rigid", "R": r_rigid},  # [  9  16]
        {"type": "rigid", "R": r_rigid},  # [ 10  17]
        {"type": "rigid", "R": r_rigid},  # [ 11  18]
        {"type": "rigid", "R": r_rigid},  # [ 12  19]
        {"type": "rigid", "R": r_rigid},  # [ 13  20]
        {"type": "rigid", "R": r_rigid},  # [ 14  20]
        {"type": "rigid", "R": r_rigid},  # [ 14  21]
        {"type": "rigid", "R": r_rigid},  # [ 15  21]
        {"type": "rigid", "R": r_rigid},  # [ 15  22]
        {"type": "rigid", "R": r_rigid},  # [ 16  22]
        {"type": "rigid", "R": r_rigid},  # [ 16  23]
        {"type": "rigid", "R": r_rigid},  # [ 17  23]
        {"type": "rigid", "R": r_rigid},  # [ 17  24]
        {"type": "rigid", "R": r_rigid},  # [ 18  24]
        {"type": "rigid", "R": r_rigid},  # [ 18  25]
        {"type": "rigid", "R": r_rigid},  # [ 19  25]
        {"type": "rigid", "R": r_rigid},  # [ 20  26]
        {"type": "rigid", "R": r_rigid},  # [ 21  27]
        {"type": "rigid", "R": r_rigid},  # [ 22  28]
        {"type": "rigid", "R": r_rigid},  # [ 23  29]
        {"type": "rigid", "R": r_rigid},  # [ 24  30]
        {"type": "rigid", "R": r_rigid},  # [ 25  31]
        {"type": "rigid", "R": r_rigid},  # [ 26  32]
        {"type": "rigid", "R": r_rigid},  # [ 26  33]
        {"type": "rigid", "R": r_rigid},  # [ 27  33]
        {"type": "rigid", "R": r_rigid},  # [ 27  34]
        {"type": "rigid", "R": r_rigid},  # [ 28  34]
        {"type": "rigid", "R": r_rigid},  # [ 28  35]
        {"type": "rigid", "R": r_rigid},  # [ 29  35]
        {"type": "rigid", "R": r_rigid},  # [ 29  36]
        {"type": "rigid", "R": r_rigid},  # [ 30  36]
        {"type": "rigid", "R": r_rigid},  # [ 30  37]
        {"type": "rigid", "R": r_rigid},  # [ 31  37]
        {"type": "rigid", "R": r_rigid},  # [ 31  38]
        {"type": "rigid", "R": r_rigid},  # [ 32  39]
        {"type": "rigid", "R": r_rigid},  # [ 33  40]
        {"type": "rigid", "R": r_rigid},  # [ 34  41]
        {"type": "rigid", "R": r_rigid},  # [ 35  42]
        {"type": "rigid", "R": r_rigid},  # [ 36  43]
        {"type": "rigid", "R": r_rigid},  # [ 37  44]
        {"type": "rigid", "R": r_rigid},  # [ 38  45]
        {"type": "rigid", "R": r_rigid},  # [ 39  46]
        {"type": "rigid", "R": r_rigid},  # [ 40  46]
        {"type": "rigid", "R": r_rigid},  # [ 40  47]
        {"type": "rigid", "R": r_rigid},  # [ 41  47]
        {"type": "rigid", "R": r_rigid},  # [ 41  48]
        {"type": "rigid", "R": r_rigid},  # [ 42  48]
        {"type": "rigid", "R": r_rigid},  # [ 42  49]
        {"type": "rigid", "R": r_rigid},  # [ 43  49]
        {"type": "rigid", "R": r_rigid},  # [ 43  50]
        {"type": "rigid", "R": r_rigid},  # [ 44  50]
        {"type": "rigid", "R": r_rigid},  # [ 44  51]
        {"type": "rigid", "R": r_rigid},  # [ 45  51]
        {"type": "rigid", "R": r_rigid},  # [ 46  52]
        {"type": "rigid", "R": r_rigid},  # [ 47  53]
        {"type": "rigid", "R": r_rigid},  # [ 48  54]
        {"type": "rigid", "R": r_rigid},  # [ 49  55]
        {"type": "rigid", "R": r_rigid},  # [ 50  56]
        {"type": "rigid", "R": r_rigid},  # [ 51  57]
        {"type": "rigid", "R": r_rigid},  # [ 52  58]
        {"type": "rigid", "R": r_rigid},  # [ 52  59]
        {"type": "rigid", "R": r_rigid},  # [ 53  59]
        {"type": "rigid", "R": r_rigid},  # [ 53  60]
        {"type": "rigid", "R": r_rigid},  # [ 54  60]
        {"type": "rigid", "R": r_rigid},  # [ 54  61]
        {"type": "rigid", "R": r_rigid},  # [ 55  61]
        {"type": "rigid", "R": r_rigid},  # [ 55  62]
        {"type": "rigid", "R": r_rigid},  # [ 56  62]
        {"type": "rigid", "R": r_rigid},  # [ 56  63]
        {"type": "rigid", "R": r_rigid},  # [ 57  63]
        {"type": "rigid", "R": r_rigid},  # [ 57  64]
        {"type": "rigid", "R": r_rigid},  # [ 58  65]
        {"type": "rigid", "R": r_rigid},  # [ 59  66]
        {"type": "rigid", "R": r_rigid},  # [ 60  67]
        {"type": "rigid", "R": r_rigid},  # [ 61  68]
        {"type": "rigid", "R": r_rigid},  # [ 62  69]
        {"type": "rigid", "R": r_rigid},  # [ 63  70]
        {"type": "rigid", "R": r_rigid},  # [ 64  71]
        {"type": "rigid", "R": r_rigid},  # [ 65  72]
        {"type": "rigid", "R": r_rigid},  # [ 66  72]
        {"type": "rigid", "R": r_rigid},  # [ 66  73]
        {"type": "rigid", "R": r_rigid},  # [ 67  73]
        {"type": "rigid", "R": r_rigid},  # [ 67  74]
        {"type": "rigid", "R": r_rigid},  # [ 68  74]
        {"type": "rigid", "R": r_rigid},  # [ 68  75]
        {"type": "rigid", "R": r_rigid},  # [ 69  75]
        {"type": "rigid", "R": r_rigid},  # [ 69  76]
        {"type": "rigid", "R": r_rigid},  # [ 70  76]
        {"type": "rigid", "R": r_rigid},  # [ 70  77]
        {"type": "rigid", "R": r_rigid},  # [ 71  77]
        {"type": "rigid", "R": r_rigid},  # [ 72  78]
        {"type": "rigid", "R": r_rigid},  # [ 73  79]
        {"type": "rigid", "R": r_rigid},  # [ 74  80]
        {"type": "rigid", "R": r_rigid},  # [ 75  81]
        {"type": "rigid", "R": r_rigid},  # [ 76  82]
        {"type": "rigid", "R": r_rigid},  # [ 77  83]
        {"type": "rigid", "R": r_rigid},  # [ 78  84]
        {"type": "rigid", "R": r_rigid},  # [ 78  85]
        {"type": "rigid", "R": r_rigid},  # [ 79  85]
        {"type": "rigid", "R": r_rigid},  # [ 79  86]
        {"type": "rigid", "R": r_rigid},  # [ 80  86]
        {"type": "rigid", "R": r_rigid},  # [ 80  87]
        {"type": "rigid", "R": r_rigid},  # [ 81  87]
        {"type": "rigid", "R": r_rigid},  # [ 81  88]
        {"type": "rigid", "R": r_rigid},  # [ 82  88]
        {"type": "rigid", "R": r_rigid},  # [ 82  89]
        {"type": "rigid", "R": r_rigid},  # [ 83  89]
        {"type": "rigid", "R": r_rigid},  # [ 83  90]
        {"type": "rigid", "R": r_rigid},  # [ 84  91]
        {"type": "rigid", "R": r_rigid},  # [ 85  92]
        {"type": "rigid", "R": r_rigid},  # [ 86  93]
        {"type": "rigid", "R": r_rigid},  # [ 87  94]
        {"type": "rigid", "R": r_rigid},  # [ 88  95]
        {"type": "rigid", "R": r_rigid},  # [ 89  96]
        {"type": "rigid", "R": r_rigid},  # [ 90  97]
        {"type": "rigid", "R": r_rigid},  # [ 91  98]
        {"type": "rigid", "R": r_rigid},  # [ 92  98]
        {"type": "rigid", "R": r_rigid},  # [ 92  99]
        {"type": "rigid", "R": r_rigid},  # [ 93  99]
        {"type": "rigid", "R": r_rigid},  # [ 93 100]
        {"type": "rigid", "R": r_rigid},  # [ 94 100]
        {"type": "rigid", "R": r_rigid},  # [ 94 101]
        {"type": "rigid", "R": r_rigid},  # [ 95 101]
        {"type": "rigid", "R": r_rigid},  # [ 95 102]
        {"type": "rigid", "R": r_rigid},  # [ 96 102]
        {"type": "rigid", "R": r_rigid},  # [ 96 103]
        {"type": "rigid", "R": r_rigid},  # [ 97 103]
        {"type": "rigid", "R": r_tube_in},  # [105 104] ###################################################
        {"type": "rigid", "R": r_bend},  # [104   2]
        {"type": "rigid", "R": r_bend},  # [104   3]
        {"type": "rigid", "R": r_bend},  # [ 98 106]
        {"type": "rigid", "R": r_bend},  # [ 99 106]
        {"type": "rigid", "R": r_tube_out},  # [106 107]
        {"type": "rigid", "R": r_bend},  # [100 108]
        {"type": "rigid", "R": r_bend},  # [101 108]
        {"type": "rigid", "R": r_tube_out},  # [108 109]
        {"type": "rigid", "R": r_bend},  # [102 110]
        {"type": "rigid", "R": r_bend},  # [103 110]
        {"type": "rigid", "R": r_tube_out},  # [110 111]
    ]

    return channel_laws

